# question.yml
name: ❓ Question
description: Ask a question about this project
title: "[Question]: "
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question! Please make sure you've searched existing issues and discussions first.
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please provide as much detail as possible to help us provide a good answer.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you using?
      placeholder: "e.g., v1.0.0"
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about your question here.
  - type: checkboxes
    id: research
    attributes:
      label: Research
      options:
        - label: I have searched the existing issues and discussions
          required: true
        - label: I have read the documentation
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this question, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true