name: Distribute common org files

on:
  workflow_dispatch: {} #to enable manual triggering of the action
jobs:

  ###################################################
  # Library related jobs
  ###################################################

  # This job deploys the files:
  # - workflows/libraries/release-library.yml, 
  # - workflows/libraries/lint-repo.yml, 
  # - workflows/libraries/build-library.yml
  # to all repositories with the topic 'library'
  deploy_library_workflows:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Replicating global workflow
          uses: derberg/manage-files-in-multiple-repositories@v2
          with:
            github_token: ${{ secrets.DEPLOY_KEY }}
            patterns_to_include: files/libraries/workflows/release-library.yml, files/libraries/workflows/lint-repo.yml, files/libraries/workflows/build-library.yml
            destination: .github/workflows
            topics_to_include: library
            exclude_private: false
            exclude_forked: true
            committer_username: simatic-ax-bot
            commit_message: "ci: distribute workflows for libraries"
  
  # This job deploys the files:
  # - files/libraries/.gitattributes, 
  # - files/libraries/.gitignore, 
  # - files/libraries/.markdownlint.yml
  # to all repositories with the topic 'library'
  deploy_common_files:

      runs-on: ubuntu-latest
      needs: deploy_library_workflows
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Replicating global workflow
          uses: derberg/manage-files-in-multiple-repositories@v2
          with:
            github_token: ${{ secrets.DEPLOY_KEY }}
            patterns_to_include: files/libraries/.gitattributes, files/libraries/.gitignore, files/libraries/.markdownlint.yml
            topics_to_include: library
            destination: .
            exclude_private: false
            exclude_forked: true
            committer_username: simatic-ax-bot
            commit_message: "ci: distribute common files"

  ###################################################
  # application examples related jobs
  ###################################################

  ###################################################
  # Template related jobs
  ###################################################

  ###################################################
  # Organization related jobs
  ###################################################

  # This job deploys the file:
  # LICENSE.md to ALL repositories
  deploy_license_file:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Replicating global workflow
          uses: derberg/manage-files-in-multiple-repositories@v2
          with:
            github_token: ${{ secrets.DEPLOY_KEY }}
            patterns_to_include: 'LICENSE.md'
            exclude_private: false
            exclude_forked: true
            committer_username: simatic-ax-bot
            commit_message: "ci: update license"