name: Check Markdown Links

on:
  push:
  workflow_dispatch:

jobs:
  check-links:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress '**/*.md'
          fail: true
          format: markdown
          config: |
            exclude = [
              "^https://code\\.siemens\\.com"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}